feat: Add reviews commands to the bot
OqixDevs/OqixTS pull request #101
Opened 2023-12-14 19:13 UTC by mimotej

# Related issues
Resolves: https://github.com/OqixDevs/OqixTS/issues/85

# Type of pull request
- [ ] New feature
- [ ] Bug fix
- [ ] Refactoring
- [x] Feature update
- [ ] Other

# Describe your PR in detail
This feature adds option to review courses with option to rate these reviews.
Adding reviews:
![Kooha-2023-12-14-20-08-52](https://github.com/OqixDevs/OqixTS/assets/47832967/d4ea41ca-e345-4506-b9e5-d09c0a8937e6)
Displaying and rating reviews:
![Kooha-2023-12-14-20-11-18](https://github.com/OqixDevs/OqixTS/assets/47832967/2bb066de-47c2-4e69-997e-be09a2e66b04)

2024-01-17 14:39 UTC, xvanick1 commented on src/commands/review.ts
> +                content: `You have already submitted review fro subject ${subjectCode}.`,
typo 'fro'

2024-01-17 14:41 UTC, xvanick1 requested changes
Looks, good. Found just a small typo.

2024-01-21 12:21 UTC, mimotej commented on src/commands/review.ts
> +                content: `You have already submitted review fro subject ${subjectCode}.`,
Resolved

2024-01-21 12:48 UTC, xvanick1 approved these changes
/lgtm

2024-01-21 12:52 UTC, merged