Add nodemon and .prettierignore
OqixDevs/OqixTS pull request #34
Opened 2022-07-16 17:44 UTC by hortjar

Adds `nodemon` package and corresponding script `npm run dev` script. Nodemon restarts the app every time a change in `src/` folder is detected

`.prettierignore` is set to ignore `*.json`, `*.md`, and `dot` files to not lint them wrongly according to `.prettierrc` rules

2022-07-16 18:12 UTC, mimotej requested changes

2022-07-16 18:12 UTC, mimotej commented on package.json
> +      "url": "https://github.com/xvanick1/OqixTS/issues"
Could you remove this space? I don't think this change is necessary...

2022-07-17 07:10 UTC, mimotej commented
/lgtm

2022-07-17 07:11 UTC, mimotej approved these changes

2022-07-17 08:19 UTC, xvanick1 approved these changes
lgtm

2022-07-17 08:20 UTC, merged